server:
  port: 8080
spring:
  application:
    name: reggie_take_out
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://114.115.162.41:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: caibi
      password: tmq@19950529
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: assign_id

# 自定义配置
reggie:
  unfiltered:
    paths:
      - /employee/login
      - /employee/logout
      - /employee/layout
      - /backend/**
      - /front/**
      - /common/**
      - /swagger-ui.html
      - /user/code
      - /user/login
  dump:
    dish:
      base-path: /Users/mingqing/Documents/study/project/reggie_take_out/src/main/resources/dump/dish/